name: Create Release
on:
  workflow_dispatch:
    inputs:
        tag:
            description: 'Tag to create release for'
            required: true
            default: 'v0.0.0'
  push:
    tags:
      - 'v*.*.*'
env:
  urdf_file_path: urdf/turtlebot3_burger.urdf.xacro
jobs:
  get_derived_names:
    outputs:
        tag: ${{ steps.derive_names.outputs.tag }}
        repo_name: ${{ steps.derive_names.outputs.repo_name }}
        urdf_source_file_path: src/${{ steps.derive_names.outputs.repo_name }}/${{ env.urdf_file_name }}
        urdf_artifact_file: ${{ steps.derive_names.outputs.urdf_artifact_file }}
        urdf_artifact_key: ${{ steps.derive_names.outputs.urdf_artifact_key }}
        docker_artifact_key: ${{ steps.derive_names.outputs.docker_artifact_key }}
        docker_image_name: ${{ steps.derive_names.outputs.repo_name }}
        docker_image_file: ${{ steps.derive_names.outputs.docker_image_file }}
    runs-on: ubuntu-latest
    steps:
      - name: Derive Names
        id: derive_names
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=v0.0.0" >> $GITHUB_OUTPUT
          fi
          
          repo_name=$(echo "${{ github.repository }}" | sed -e 's/.*\///g')
          echo "repo_name=${repo_name}" >> $GITHUB_OUTPUT
          echo "urdf_artifact_file=${repo_name}_urdf.tar.gz" >> $GITHUB_OUTPUT
          echo "urdf_artifact_key=${repo_name}_urdf" >> $GITHUB_OUTPUT
          echo "docker_artifact_key=${repo_name}_docker" >> $GITHUB_OUTPUT
          echo "docker_image_file=${{ github.repository_owner }}-${repo_name}_${tag}_docker.tar" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
  generate_urdf:
    runs-on: ubuntu-latest
    needs: [get_derived_names]
    container: ros:iron
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: src/turtlebot3_description
    - name: install dependencies
      run:  sudo apt-get update && rosdep update && rosdep install --from-paths src -r -y
    - name: Generate URDF files
      shell: bash
      run: |
        source /opt/ros/iron/setup.bash
        colcon build --packages-select ${{ needs.get_derived_names.outputs.repo_name }}
        source ./install/setup.bash
        xacro ${{ needs.get_derived_names.outputs.urdf_source_file_path }} -o ${{ needs.get_derived_names.outputs.urdf_artifact_file }}
    - name: Upload URDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.get_derived_names.outputs.urdf_artifact_key }}
        path: ${{ needs.get_derived_names.outputs.urdf_artifact_file }}

  build_docker:
    runs-on: ubuntu-latest
    needs: [get_derived_names, get_derived_names]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker image
      id: build_docker_image
      run: |
        tagged_image_name=${{ needs.get_derived_names.outputs.docker_image_name }}:${{ needs.get_derived_names.outputs.tag }}
        docker build -t ${tagged_image_name} -f ./docker/Dockerfile .
    - name: Save Docker image as tar
      id: upload_docker_image
      run: |
        docker save ${{ steps.build_docker_image.outputs.tagged_image_name }} -o ${{ needs.get_derived_names.outputs.docker_image_file }}
    - name: Upload Docker image tar artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ needs.get_derived_names.outputs.docker_artifact_key }}
        path: ${{ needs.get_derived_names.outputs.docker_image_file }}

  create_release:
    runs-on: ubuntu-latest
    needs: [get_derived_names, generate_urdf, build_docker]
    env:
      source_archive: ${{ github.repository_owner }}-${{ needs.get_derived_names.outputs.repo_name }}_${{ needs.get_derived_names.outputs.tag }}_source.tar.gz
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download URDF artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.get_derived_names.outputs.urdf_artifact_key }}
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.get_derived_names.outputs.docker_artifact_key }}
    - name: Archive source code
      run: |
        git archive --format=tar.gz --output=${{ env.source_archive }} ${{ needs.get_derived_names.outputs.tag }}
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ needs.generate_urdf.outputs.artifact_file }}
          ${{ env.source_archive }}
          ${{ needs.build_docker.outputs.image_file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
