name: Create Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate_urdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
          ros-iron-xacro

    - name: setup ROS
      uses: ros-tooling/action-ros-setup@v0.1
      with:
        required-ros-distributions: iron

    - name: Generate URDF files
      run: |
        colcon build --packages-select turtlebot3_description
        xacro urdf/turtlebot3_burger_urdf.xacro -o turtlebot3.urdf
        stat turtlebot3.urdf
        tar -czvf turtlebot3_urdf.tar.gz install/turtlebot3_description/

    - name: Upload URDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: turtlebot3_urdf
        path: turtlebot3_urdf.tar.gz

  build_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t your-docker-image-name:latest .

    # Save Docker image to a tar file
    - name: Save Docker image as tar
      run: |
        docker save your-docker-image-name:latest -o your-docker-image-name_${{ github.ref_name }}.tar

    - name: Upload Docker image tar artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker_image
        path: your-docker-image-name_${{ github.ref_name }}.tar

  create_release:
    runs-on: ubuntu-latest
    needs: [generate_urdf, build_docker]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Download artifacts from previous jobs
    - name: Download URDF artifact
      uses: actions/download-artifact@v4
      with:
        name: turtlebot3_urdf

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker_image

    - name: Archive source code
      run: |
        git archive --format=tar.gz --output=source_code_${{ github.ref_name }}.tar.gz ${{ github.ref_name }}

    # Create release and upload artifacts
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          turtlebot3_urdf.tar.gz
          source_code_${{ github.ref_name }}.tar.gz
          your-docker-image-name_${{ github.ref_name }}.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
