name: ROS2 CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:iron
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            ros-iron-xacro \
            python3-colcon-common-extensions \
            python3-colcon-test-result && \
            python3 -m pip install colcon-coveragepy-result
      - name: run CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: turtlebot3_description
          target-ros2-distro: iron
  lint_and_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    container: ros:iron
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lint with ament
      uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: flake8
        package-name: turtlebot3_description
