name: ROS2 CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-noble-ros-jazzy-ros-base
    steps:
      - name: setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: iron
      - name: checkout code
        uses: actions/checkout@v4
      - name: run CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: turtlebot3_description
          target-ros2-distro: iron
  lint_and_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    container: ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-noble-ros-jazzy-ros-base
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup ROS2  
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: iron
    - name: Lint with ament
      uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: flake8
        package-name: turtlebot3_description
